### ISSUE TITLE
Starting Loss

### ISSUE THREAD

**Issue by DatNigazz** [rojagtap/abstractive_summarizer#6]
I copied your code and i´m trying to execute, but my starting Loss is like 10, while yours on first epoch is 2.x
Why does this happen?

**Comment by rojagtap** [comment]
Hey sorry for the delay, I may have missed the notification. Regarding your question, are you using the same dataset as mine?

**Comment by DatNigazz** [comment]
Yes, i'm using the same dataset.
https://www.kaggle.com/shashichander009/inshorts-news-data

**Comment by rojagtap** [comment]
I too, started with a loss of around 10. Since I use Google Colab for training, the session resets after a few hours. So there is a possibility that I may have trained the model for a few epochs earlier, and what you see is the loss starting from a much later epoch.

To support my point:
- The first save is already the 5th checkpoint: `Saving checkpoint for epoch 5 at checkpoints/ckpt-5`
- `Latest checkpoint restored!!` indicates the weights have been loaded from some checkpoint.

Apologies if the code was misleading, but it's really difficult to work with limited resources.
I hope this clears your doubts.
